version: '3'

services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    restart: always # redémarrage automatique
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes: # partage un volume entre le notebook et l'ide par ex
      - ./app:/app

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    restart: always # redémarrage automatique
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    volumes:
      - ./app:/app

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    restart: always # redémarrage automatique
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    volumes:
      - ./app:/app

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    restart: always # redémarrage automatique
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    volumes:
      - ./app:/app

